demisto/sane-reports

- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/components/Sections/SectionDuration.js
- src/components/Sections/SectionDuration.less
- src/components/Sections/SectionNumber.less
- src/components/Sections/index.js
- src/constants/Constants.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
labels can be customized changing `daysLabel`, `hoursLabel`, `minutesLabel` in the json file:
```
"layout": {
"chartProperties": {
"daysLabel": "DAYS",
"hoursLabel": "HOURS",
"minutesLabel": "MIN"
}
},
```
> Duration and fixes

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/components/Sections/SectionList.js
Sometimes users run to empty reports when widgets are empty. Make sure all charts accept empty values.
> avoid null errors

- .circleci/config.yml
Can use node 9 only (others conflict with npm version and cause errors)
> CircleCI use latest npm

- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/constants/Constants.js
- tests/containers/ReportContainer_spec.js
fixed sometimes data in table is a complex object instead of array causing miscalculation of the rows.
fixes demisto/etc#13103
example:
> show default percentage label + minor table fix

- package.json
fix `node[38289]: ../src/node_file.cc:943:void node::fs::Stat(const FunctionCallbackInfo<v8::Value> &): Assertion (argc) == (4)' failed...` on `npm run production`
> fix postcss-cssnext cause build failure

- package.json
- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionText.less
fix text fields does not wrap on long spaceless text.
added npm install to service make
fix table height create empty pages
> table report fix + text field wrap

- package.json
- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
use `webpack-dev-server` stable version (https://github.com/webpack/webpack-dev-server/issues/1355#issuecomment-406541618)
fix widget number not showing regression
> fix number widget position after height changes

- package.json
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionBarChart.less
- src/components/Sections/SectionChart/SectionChart.js
- src/components/Sections/SectionChart/SectionChart.less
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionLineChart.less
- src/components/Sections/SectionChart/SectionPieChart.less
- src/components/Sections/SectionList.js
- src/index.js
- fixed height miss-render on charts
- fixed list section should accept column strings as well as objects
- added support for phantomJS using `core-js` including es6 to support backward compatibility
> Chart overlap fix, list section custom column support, phatomJS support

- src/components/Sections/SectionChart/SectionLineChart.js
diff between dates should always ceil to highest difference to count frames.
> round date chart difference fix partial dates

- reportService/package.json
- reportService/reportsServer.js
- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionTable.js
- src/utils/layout.js
- use reports service with extra memory and no navigation timeout for big reports
- added max columns for section table which defaults to the max columns possible under the page size
- fixed table line breaks not working when only one word
fixes: https://github.com/demisto/etc/issues/19600
> Handle big size reports & table fixes

- src/components/Layouts/ReportLayout.less
remove force font family and force on body only. This will be overridden by any style given to section/items (since it apply it directly on the element with higher priority).
fixes https://github.com/demisto/sane-reports/issues/83
```
[{
"type": "html",
"data": "<span style=\"font-family:Arial\">hello <strong>bold</strong> hello</span>",
"layout": {
"rowPos": 8200,
"columnPos": 100,
"tableClasses": "right aligned",
"style": {
"color": "#555555",
"fontSize": 14,
"backgroundColor": "#ffffff",
"padding": 6,
"border": "1px solid #d4d4d4",
"marginTop": -9
}
}
},
{
"type": "markdown",
"data": "hello **bold** hello",
"layout": {
"rowPos": 8200,
"columnPos": 100,
"tableClasses": "right aligned",
"style": {
"color": "#555555",
"fontSize": 14,
"fontFamily": "Arial",
"backgroundColor": "#ffffff", …
```
> remove force font family on all elements

- index.template.html
- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionChart/ChartLegend.js
- src/components/Sections/SectionChart/ChartLegend.less
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
- added automatic capitalize on chart legends with capitalize option in legendstyle
```
"legendStyle": {
"capitalize": false
}
```
defaults to true if not specified
- fixed non-latin letters did not resolve if embedded data was too big
> Fix non latin letters not appearing in some cases + chart legend capitalization

- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/constants/Constants.js
- src/containers/ReportContainer.js
- src/index.js
- using column based page break to determine required page break and widget's offset in the layout dynamically, thus avoiding stacked widgets causing incorrect heights.
- removed isAutoHeightLayout flag no longer needed.
- added default page dimensions for debugging or when missing from api.
Tested with old reports, widgets layout, and investigation layout.
> Page break calculations fixes + markdown section oveflow bounds

- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionChart/SectionBarChart.js
fix layout holes may cause sections to misscaclculated their total height
removed cartesian grid from column chart
> Fix automatic height layout issue + remove cartesian grid from column chart

- reportService/reportsServer.js
- src/components/Layouts/ReportLayout.js
- src/components/Sections/ItemsSection.js
- src/components/Sections/ItemsSection.less
- src/components/Sections/SectionGroupedList.js
- src/components/Sections/SectionGroupedList.less
- src/components/Sections/SectionMarkdown.js
- src/css/variables.less
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
- fixed overall sections and section items paddings
- fixed section items auto height sometimes does not apply
- fixed section item description position
- added grouped list bold title
- avoid stacking tables in section markdown too avoid miss calculation by the css media query
- use better default margins of 0.5 inch for better standard side margin
- added test cases
> section items height fixes and cosmetic changes 

- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionTable.js
- add safe check for section table data
- ignore line chart legend when only one line. used to protect the line chart displaying incorrect values when legend is provided but not needed.
> Protect line chart and table

- src/components/Sections/SectionChart/ChartLegend.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
- allow chart legend to display zero value on all layouts and charts
- test check on chart legend
- added util to help test chart legends based on given element and data
> allow chart legend to display zero value + test check on chart legend

- src/components/Sections/SectionList.less
added word wrap for sections list to avoid overflow
> added word wrap to section list

- src/components/Sections/SectionList.less
- src/utils/layout.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
fixed charts are not considered stack based on their data + check in test
add slight padding to lists sections
before:
after:
> Fix stack charts not considered stack based on data

- src/components/Sections/SectionChart/SectionLineChart.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/34288
Given:
```
"layout": {
"chartProperties": {
"axis": {
"x": {
"label": "mambaX"
},
"y": {
"label": "mambaY"
}
},
...
},
...
}
```
**=>**
> Section Line Chart - support axis labeling

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
related <https://github.com/demisto/etc/issues/34536>
server PR | [link](https://github.com/demisto/server/pull/18218)
client PR | [link](https://github.com/demisto/web-client/pull/7710)
y axis domain handled accordingly
> Add reference line support for line chart and horizontal bar chart

- src/components/Sections/SectionChart/SectionLineChart.js
- src/constants/Constants.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
_related to https://github.com/demisto/etc/issues/35839
related to https://github.com/demisto/web-client/pull/7865_
Given explicit SUPPORTED_TIME_FRAMES.none under timeFrame param => ignore dateTime auto formatting for line charts.
> support force input non-formatted names for date range line charts

- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionNumber.less
add border to widget number as the height and width already fixed
Fixes https://github.com/demisto/etc/issues/34232
> Fix number widget border

- src/components/Sections/SectionDuration.less
Fixes https://github.com/demisto/etc/issues/34218
branch | PR
------ | ------
web PR | [link](<https://github.com/demisto/web-client/pull/7991>)
Hide horizontal overflow for duration section
> hide overflow for duration section

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/utils/strings.js
Fixes <https://github.com/demisto/etc/issues/36649>
Web Client PR: https://github.com/demisto/web-client/pull/8225
fix line chart axis name overflow
fix bar chart axis name overflow
add ellipsis to axis names
how it looks on report now:
how it looks on the report builder:
> fix line/bar chart axis name overflow

- src/components/Sections/SectionChart/SectionBarChart.js
remove legend height from vertical bar char height 
fixes <https://github.com/demisto/etc/issues/37268>
before 
After
> fix vertical bar chart 

- src/components/Sections/SectionChart/SectionBarChart.js
Align sane report to UI logic.
when we have single bar (it is aligned to the middle of the chart) its value will overlap with the reference line title.
solution in the UI is to move the reference line title to the right side in this flow.
How it looks in report
How it looks in UI
fixes https://github.com/demisto/etc/issues/37444
> fix reference line title overlap single bar value

- src/components/Sections/SectionChart/SectionLineChart.js
Fixes https://github.com/demisto/etc/issues/37378
branch | PR
------ | ------
Web PR | [link](<https://github.com/demisto/web-client/pull/8284>)
Disable tick auto word wrap for line chart x-axis (recharts internals)
> sane - disable tick word wrap

- src/components/Sections/SectionChart/SectionLineChart.js
- tests/containers/ReportContainer_spec.js
related <https://github.com/demisto/sane-reports/pull/164>
fixes <https://github.com/demisto/etc/issues/37580>
fixes a bug(missing last date) when passing to date 
before 
after
> fix line chart - remove extra date added when no to date

- src/components/Sections/SectionNumber.js
- src/components/Sections/SectionNumber.less
- src/utils/layout.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
_Related to https://github.com/demisto/web-client/pull/8339_
Applies given style objects under layout over number/trend widgets.
→ numberStyle & titleStyle properties
**Example:**
```
{
"type": "trend",
"data": {
"currSum": 5,
"prevSum": 49
},
"layout": {
"columnPos": 2,
"currencySign": "",
"h": 1,
"i": "0c22b3d0-f5eb-11e7-92ea-eb1e1a874380",
"layout": "horizontal",
"rowPos": 0,
"style": {
"backgroundColor": null
},
"numberStyle": {
"fontSize": "40px",
"fontWeight": 300
},
"titleStyle": {
"fontSize": "34px",
"fontWeight": 400
},
"w": 3,
"valuesFormat": "decimal"
},
"query": {
"filter": {
"period": {
"fromValue": 30,
"by": "day"
},
"fromDate": "2017-12-10T22:00:00Z",
"toDate": null
}
},
"automation": {
"name": "",
"args": null
},
"title": "Trend Chart"
}
```
**Out:**
> Number widget optional styling support

- src/components/Sections/SectionChart/SectionChart.js
- src/components/Sections/SectionChart/SectionChart.less
- src/components/Sections/SectionDuration.js
- src/components/Sections/SectionGroupedList.js
- src/components/Sections/SectionList.js
- src/components/Sections/SectionMarkdown.js
- src/components/Sections/SectionNumber.js
- src/components/Sections/SectionNumber.less
- src/components/Sections/SectionTable.js
- src/components/Sections/SectionTitle.js
- src/components/Sections/SectionTitle.less
- src/utils/layout.js
- src/utils/strings.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
Fixes <https://github.com/demisto/etc/issues/37804>
Related <https://github.com/demisto/etc/issues/34410#event-4857934791>
1) capitalize first letter - number widget
2) show forced time range message on charts
3) show forced time range on text \ number \ table \ list \ markdown \ duration'  widget
markdown
text
> show time range message on widgets 

- src/components/Sections/SectionTable.js
- src/utils/layout.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/38641
Given:
```
{
"type": "table",
"data": [
{
...
}
],
"layout": {
...
"headerStyle": {
"color": "maroon"
}
},
...
}
```
**→**
> optional table headers styling object

- src/components/Sections/SectionChart/ChartLegend.less
- src/components/Sections/SectionChart/SectionPieChart.less
Related https://github.com/demisto/etc/issues/39562
Pie section with vertical legend layout - change flex ration between text and value to 4:1 instead 2:1 
**Before**
**After**
> pie section change vertical legend text-value layout

- index.template.html
- reportService/reportsServer.js
- src/components/Sections/SectionMarkdown.js
- src/constants/Constants.js
- src/index.js
- src/utils/layout.js
- src/utils/reports.js
Related issue: https://github.com/demisto/etc/issues/40210
- Support markdown resources server parameter (to be sent via sanePdfReports script)
- translate any demisto markdown image source (hosted in demisto server) to the markdown resource server received via the cmd parameter.
branch | PR
------ | ------
Content PR | https://github.com/demisto/content/pull/14508
Server MR |  https://code.pan.run/xsoar/server/-/merge_requests/16194
> markdown images support

- src/components/Layouts/ReportLayout.js
- src/components/Sections/ItemsSection.less
- src/components/Sections/SectionDate.js
- src/utils/reports.js
https://github.com/demisto/etc/issues/38832
https://code.pan.run/xsoar/web-client/-/merge_requests/6658
Row fields: last field in section does not have a line under it
Style "date" and "generated by"
> Style reports layout

- src/components/Sections/ItemsSection.less
- src/components/Sections/SectionTable.js
- src/components/Sections/SectionTable.less
- src/utils/layout.js
https://github.com/demisto/etc/issues/38832
Update and remove redundant paddings (after design review)
Add empty icon and text for empty global sections (compare 'Notes' section)
Fix bug that columns metadata didn't affect table columns for section table (compare 'Indicators' section)
> Style sections

- src/components/Sections/SectionMarkdown.js
- src/components/Sections/SectionMarkdown.less
- src/css/variables.less
- src/utils/markdown.js
- templates/testLayoutMarkdownWithCodeBlock.json
- templates/testLayoutMarkdownWithCodeBlock2.json
- tests/containers/ReportContainer_spec.js
support for inline-code when using one back-tick like so:  \`...`
> adding inline-blockquote functionality

- src/components/Sections/SectionMarkdown.less
[2021-12-02_23-25-15_test.pdf](https://github.com/demisto/sane-reports/files/7645463/2021-12-02_23-25-15_test.pdf)
[2021-12-03_00-21-58_test.pdf](https://github.com/demisto/sane-reports/files/7645459/2021-12-03_00-21-58_test.pdf)
> add page-break-inside: avoid at .preplacer and img

- src/utils/reports.js
- src/utils/sort.js
- templates/testLayoutEmptyTemplate.json
- tests/containers/ReportContainer_spec.js
protect array functions like sort from non array values (null, undefined or objects) that were causing the client to fail before error boundaries
> protect all sort calls make sure its an array + test

- src/components/Sections/ItemsSection.less
> fix section item header text transform capitalized

- reportService/reportsServer.js
Fixes https://github.com/demisto/etc/issues/46284
Fix disable header - according to puppeteer docs the  `headerTemplate` option should be a valid `HTML markup` string.
Empty string fail in validation and causes the header to display default values like current date.
Relevant documentation -https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions
> fix disable header

- src/components/Sections/SectionMarkdown.less
Fixes CRTX-57370
https://jira-hq.paloaltonetworks.local/browse/CRTX-57370
revert page break inside markdowns 
Before fix 
After fix -
> fix page break inside makrdown

- src/components/Sections/ItemsSection.js
Downloading a report with an empty 'General Purpose Section' displays an error in the report.
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/9811530/incidentDailyReportTempalte.pdf)
Notes: can't use `lastRow?.index` because of it is not supported in the build proccess.
> CRTX-63401: Downloading a report with an empty 'General Purpose Section'

- src/components/Layouts/ReportLayout.less
This PR fixes overlapping issues with itemsSections and makes them breakable.
[1-master.pdf](https://github.com/demisto/sane-reports/files/9860314/1-master.pdf)
[2-master.pdf](https://github.com/demisto/sane-reports/files/9860312/2-master3-master.pdf)
[3-master.pdf](https://github.com/demisto/sane-reports/files/9860514/3-master.pdf)
[1.pdf](https://github.com/demisto/sane-reports/files/9860595/1.pdf)
[2.pdf](https://github.com/demisto/sane-reports/files/9860606/2.pdf)
[3.pdf](https://github.com/demisto/sane-reports/files/9860569/3.pdf)
> CRTX-64873: Panels are overlapping on each other

- src/utils/layout.js
Related PR: https://github.com/demisto/sane-reports/pull/230.
The scenario that `useCurrentTime` exists with a `date` doesn't exist.
It is just in case.
> CRTX-64873: Always display date in section if exists

- src/components/Sections/SectionChart/SectionLineChart.js
I generated the reported json from the issue: [incidentDailyReportTempalte.txt](https://github.com/demisto/sane-reports/files/11260877/incidentDailyReportTempalte.txt)
The generated report after these changes: [incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/11260882/incidentDailyReportTempalte.pdf)
When all the group names can't be formatted (null, number, valid string like '13/10/1992') we use the timeFrame 'none'.
This is how the report looks like without these changes / when we have any formattable name: [incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/11260931/incidentDailyReportTempalte.pdf)
> CRTX-79881: Use none timeframe when all the name are unformmatable

- index.template.html
- reportService/reportsServer.js
- src/components/Sections/SectionDate.js
- src/constants/Constants.js
- src/index.js
server already formatting the section date data.
currently, sane is formatting the data using a hard coded format and its own TZ (running machine)
> add server config support to force using server formatted time strings

- src/components/Sections/SectionDate.js
when no "data" is provided in the section and "section.layout.useCurrentTime" set to "true", the sane pass the current time as a "moment" object.
in this case we need to fall back into the formatting state and not use the "server formatted time" as it is not formatted by the server
> sectionDate validate isMoment before enforceing server formatting

- src/components/Sections/SectionTable.js
- src/utils/layout.js
Cells inside tables is getting truncated even thought `reflectDimensions` is set to true.
```
[
{
"type": "table",
"data": {
"data": [
{
"Critical Updates": "SIR0041393 - SOC was notified during the Red Team exercise, a potential compromise of Alstom application website 'solochain'. As per investigation, the website” supplychain.alstom.com” resolving to IP 81.31.28.99 and identified with multiple vulnerabilities. Remediation action is underway with application and network teams.",
"Service": "SOC"
},
{
"Critical Updates": "Logging Fluctuations in Sentinel: We have been seeing some fluctuations in the logging to Sentinel because of which multiple critical network assets have been found to be in ‘Unhealthy state’ at random times. MS Team has already been involved to identify and fix the …
```
> Reflect dimentions in table section

- src/components/Sections/SectionMarkdown.js
- src/constants/Constants.js
https://github.com/demisto/content/pull/30744/files
We added a server url to the image src when the images paths that started with `/xsoar/image` or with `acc_{name}/markdown/image`. 
In `XSOAR-NG` it works different because the path starts with `/xsoar`.
This PR handles images that the path starts also with `/xsoar`.:
> CRTX-97293: Handle images that has /xsoar prefix

- src/components/Layouts/ReportLayout.less
There is an existing fix for this issue when it appears under `react-grid-layout`. 
This PR makes it work the same in `reports-section`.
Tested on these examples to make sure this PR doesn't break anything:
- [incident_info.json](https://github.com/demisto/sane-reports/files/13349729/incident_info.json) - incident info tab with a markdown of a table and a grid field
- [investigation_summary.json](https://github.com/demisto/sane-reports/files/13349734/investigation_summary.json) - investigation summary tab
[incidentDailyReportTempalte.json](https://github.com/demisto/sane-reports/files/13403013/incidentDailyReportTempalte.json)
[before.pdf](https://github.com/demisto/sane-reports/files/13403014/before.pdf)
[after.pdf](https://github.com/demisto/sane-reports/files/13403015/after.pdf) …
> CRTX-96742: Broken tables in the PDF report Investigation summary

- src/components/Layouts/ReportLayout.less
- src/utils/layout.js
We want to avoid splitting these sections:
[incidentDailyReportTempalte.json](https://github.com/demisto/sane-reports/files/13546201/incidentDailyReportTempalte.json)
[before.pdf](https://github.com/demisto/sane-reports/files/13546200/before.pdf)
[after.pdf](https://github.com/demisto/sane-reports/files/13546199/after.pdf)
[incidentDailyReportTempalte.json](https://github.com/demisto/sane-reports/files/13546224/incidentDailyReportTempalte.json)
[before.pdf](https://github.com/demisto/sane-reports/files/13546222/before.pdf)
[after.pdf](https://github.com/demisto/sane-reports/files/13546221/after.pdf)
> CRTX-96742: Don't break certain global sections inside

- src/components/Sections/SectionChart/SectionPieChart.js
When we have a fill/color in an item we should take it from there.
How we did it in other places:
---- 
Validating with items with colors.
JSON: [CRTX-99841.json](https://github.com/demisto/sane-reports/files/13859324/CRTX-99841.json)
[CRTX-99841_before.pdf](https://github.com/demisto/sane-reports/files/13859326/CRTX-99841_before.pdf)
[CRTX-99841_after.pdf](https://github.com/demisto/sane-reports/files/13859329/CRTX-99841_after.pdf)
----
Validating with fill, color and empty use-cases.
JSON: [CRTX-99841-2.json](https://github.com/demisto/sane-reports/files/13859424/CRTX-99841-2.json)
[CRTX-99841-2-before.pdf](https://github.com/demisto/sane-reports/files/13859450/CRTX-99841-2-before.pdf)
[CRTX-99841-2-after.pdf](https://github.com/demisto/sane-reports/files/13859427/CRTX-99841-2-after.pdf) …
> CRTX-99841: PieChart | Use colors from the template

- reportService/reportsServer.js
add utf8bom to csv header when needed to support hebrew in MS Excel.
it will only be enforced when "addUtf8Bom" arg is passed by the sane script (which is affected by server config)
before:
after:
> XSUP-34767 - add utf8bom to csv header when needed

- src/components/Cells/TimerCell/TimeTicker.js
- src/components/Cells/TimerCell/TimerCell.js
- src/office/csv/CSVReport.js
- https://github.com/demisto/sane-reports/pull/247
Displaying the same data for the timer field in the CSV report just as we display in the PDF report
- Create an incident with timer fields (Containment SLA, Detection SLA...)
- Go to the incident and update the timer fields using `!startTimer` `!stopTimer` commands
- Create a report with a incidents table widget
- Generate the report using PDF/CSV formats
```
it('Generate csv report', () => {
const testTemplate = loadTemplate('testLayoutCsvWithTimers.json');
```
[testLayoutCsvWithTimers.json](https://github.com/demisto/sane-reports/files/15415601/testLayoutCsvWithTimers.json)
```
[
{
"type": "table",
"data": [
{
"Containment SLA": "Status: idle",
"Detection SLA": "Status: running ()",
"ID": "1",
"Name": "Test",
"Remediation SLA": "Status: …
```
> CRTX-90233: CSV | Support rendering SLA field in timer cell
