- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionMarkdown.js
- templates/test.json
fixes: https://github.com/demisto/server/issues/8710
> Added the ability to provide table classes to markdown section

- src/office/csv/CSVReport.js
fixes: https://github.com/demisto/server/issues/9442
> Fixed csv export

- package.json
- src/components/Sections/SectionDate.js
- src/office/csv/CSVReport.js
- templates/closureReportPart1.json
- templates/incidentDailyReportTempalte.json
- templates/mttr.json
- templates/test.json
- templates/testCSV.json
- tests/containers/ReportContainer_spec.js
fixes https://github.com/demisto/etc/issues/7648
> add timezone to reports

- reportsServer.js
calculate width and height by orientation and added support for paper size.
> page size support + fix orientation

- reportsServer.js
get image path instead image logo
> support large costumer logo

- src/components/Layouts/ReportLayout.js
Still rough because we dont know the exact height of each row but should be ok
> fix table cutoff on some reports

- src/components/Sections/SectionChart/ChartLegend.js
- src/components/Sections/SectionChart/ChartLegend.less
- src/components/Sections/SectionChart/SectionPieChart.js
fixed pie chart labels on legend issue.
added ellipsis to legend if needed.
> Legend And Pie Minor Fixes

- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionChart/ChartLegend.js
- src/components/Sections/SectionChart/ChartLegend.less
- src/components/Sections/SectionNumber.js
- fixed legend ellipsis.
- added sign and align for number.
> multiple fixes for layout reports

- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionChart/ChartLegend.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/components/Sections/SectionTable.js
- src/constants/Constants.js
support new widgets architecture + bar chart legend fix + increased pie labels offset
example:
> New widgets architecture + fixes

- src/components/Sections/SectionChart/SectionBarChart.js
`Object.values` is not supported by phantomJS causing failures in reports using phantomJS
> Bar chart fix

- README.md
- reportService/reportsServer.js
- reportsServer.js
- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/constants/Constants.js
added logo section.
change header style + report stylings.
added disable header option to chromium and phantomjs.
added footer logos when disable headers to chromium and phantomjs.
> added logo section and enhancements 

- package.json
- src/components/Sections/SectionMarkdown.js
- added link definition for markdown.
- fix link in markdown table break markdown.
> Markdown link table fix

- package.json
- src/components/Sections/SectionChart/SectionBarChart.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
fixed stacked column chart failed to render + test
fixed package json web pack.
> fix stacked column chart issues

- .circleci/config.yml
- package.json
- reportService/package.json
Upgraded pkg library to support node 10.
> Fix make process

- .circleci/config.yml
- reportService/reportsServer.js
use `fs.writeFileSync` instead of changed `fs.write`
use `unlinkSync` instead of changed `fs.remove`
use node LTS version 10.15.3
> Use LTS node version and fix fs usage

- src/components/Sections/SectionMarkdown.js
- templates/test.json
> fix empty table cell break markdown + test

- src/components/Layouts/ReportLayout.js
- src/components/Sections/SectionTable.js
> No results found - dynamic

- package.json
Upgrade lodash version due to:
> Upgrade lodash version

- index.template.html
- reportService/reportsServer.js
- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionList.less
- src/containers/ReportContainer.js
- src/index.js
added auto hight flag to force auto height when using a layout report or not added missing padding to section
fixed list widget does not stretch full width
> add optional auto height + fix list widget size

- src/components/Sections/SectionMarkdown.js
- src/utils/markdown.js
In report we will disp[lay only the message as a span
> Markdown buttons in reports

- package.json
- src/components/Sections/SectionMarkdown.js
- src/utils/layout.js
Layout should have `doNotShowEmoji: true` if want to disable emoji rendering in markdown
> Add the ability to now show emoji in markdown section

- src/components/Sections/SectionTable.js
> use pre-line to consider new lines within table, overflow lines in words if possible

- templates/test.json
added css usage examples in test.json text.
related to https://github.com/demisto/sane-reports/issues/86
> add css section examples in test.json

- src/office/csv/CSVReport.js
- src/utils/reports.js
- templates/testCSV.json
Fixes: https://github.com/demisto/etc/issues/19145
Will display it as text.
> Added support for markdown section in csv

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/utils/colors.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
- fixed pie, line and bar does not cast empty values to none
- fixed none color is not using default color
- test
> Blank to None legend issue fix

- reportService/reportsServer.js
- src/components/Layouts/ReportLayout.js
- added disable shm and auto reload for better performance when using chrome
- fixed an issue with dynamic height not using max offset for each section width
> Add default args to chrome for performance + height calculation fix

- src/components/Sections/SectionChart/SectionLineChart.js
fixed single line was taking incorrect properties instead of using the default `data`.
> Line chart single fix

- src/components/Sections/SectionChart/SectionLineChart.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
> fixed bug inner group in line chart did not take color from group

- reportService/reportsServer.js
add a check to a case of empty data
> fix empty csv reports

- src/office/csv/CSVReport.js
Fixes <https://github.com/demisto/etc/issues/27315>
fix readableHeaders on csv report
fix markdown on csv report
> fix markdown and readableHeaders

- src/components/Sections/SectionChart/SectionBarChart.js
set width by category text length - not more than (dimention.width / 3)
Fixes <https://github.com/demisto/etc/issues/27340>
> set width by category text length

- src/components/Sections/SectionTable.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
> fix empty array columns does not render table section with default columns + test

- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionNumber.js
- src/components/Sections/SectionNumber.less
Fixes <https://github.com/demisto/etc/issues/29416>
branch | PR
------ | ------
server PR | <https://github.com/demisto/server/pull/16634>
add background color in case of widget color threshold is enabled
> support background color for SectionNumber widget

- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
remove section layout padding not used and decrease dynamic padding to better match page sizes
> adjust padding to better match sections to page

- src/office/csv/CSVReport.js
Fixes <https://github.com/demisto/etc/issues/31454>
> fix equal sign to align export incidents csv reports

- src/components/Sections/SectionChart/SectionLineChart.js
Fixes https://github.com/demisto/etc/issues/33071
Before:
After:
> single line chart render issue due to referenced data prop mutation

- reportService/package.json
- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/constants/Constants.js
- src/utils/reports.js
- templates/templateProvider.js
- templates/testLayoutWithPageBreaks.json
- tests/containers/ReportContainer_spec.js
Related https://github.com/demisto/etc/issues/35023
Related https://github.com/demisto/etc/issues/30243
Related https://github.com/demisto/etc/issues/35024
1. Fix table break on table widgets & markdown 
2. show table header
3. add support for  auto page break 
old 
fixed
> Fix auto page break

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionBarChart.less
- src/constants/Constants.js
- src/utils/strings.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
show values on bar graph
related <https://github.com/demisto/etc/issues/33259>
+ fix legend position
> show values on bar graph

- src/components/Sections/SectionChart/ChartLegend.js
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionLineChart.less
- src/components/Sections/SectionChart/SectionPieChart.js
- src/components/Sections/SectionDuration.js
- src/components/Sections/SectionDuration.less
- src/constants/Constants.js
- src/utils/strings.js
- src/utils/ticks.js
- templates/templateProvider.js
- templates/testLayoutDuration.json
- tests/containers/ReportContainer_spec.js
- tests/helpers/helper.js
Fixes https://github.com/demisto/etc/issues/34745
PR https://github.com/demisto/web-client/pull/7822
**Widget legends https://github.com/demisto/etc/issues/32166 -** 
Set legend shape to be square according to the requirement that legends should all share the same shape 
**Responsive X-Axis https://github.com/demisto/etc/issues/30725 -** 
Related to Bar & Line charts -  make x-axis responsive by supporting tick interval and angle.
**Duration widget https://github.com/demisto/etc/issues/33533 -**
Support duration formats
**Limit widget - show others https://github.com/demisto/etc/issues/33591 -**
Support hiding 'Others' group
> Web client widget enhancements

- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionChart/ChartLegend.less
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionBarChart.less
- src/components/Sections/SectionChart/SectionChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionLineChart.less
- src/components/Sections/SectionChart/SectionPieChart.js
- src/components/Sections/SectionChart/SectionPieChart.less
- src/constants/Constants.js
- src/utils/layout.js
- src/utils/reports.js
- tests/containers/ReportContainer_spec.js
related <https://github.com/demisto/etc/issues/33270#issuecomment-817542168>
Related <https://github.com/demisto/etc/issues/35454>
1. Add border to widgets 
+ tables 
2. fix padding legend column chart 
3. Add support for force height - column chart & line chart 
4. add support to disable force height for tables 
Force full table - enabled 
Force full table - disabled 
Vertical bars  stacked & unstacked - 
report builder - 
after fix - 
[localhost.pdf](https://github.com/demisto/sane-reports/files/6323077/localhost.pdf)
before fix -
Horizontal bar - 
report builder - 
after fix - 
before fix -  
_____________
Pie Chart vertical & horizontal 
report builder - vertical 
report builder horizontal - 
after fix - 
[localhost - pie.pdf](https://github.com/demisto/sane-reports/files/6323438/local …
> Reports support force height

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionNumber.js
- src/utils/layout.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/34354
Fixes https://github.com/demisto/etc/issues/34877
> section number formatting & section bar chart axis labelling

- src/constants/Constants.js
- src/utils/strings.js
- templates/testLayoutDuration.json
- tests/containers/ReportContainer_spec.js
fixes https://github.com/demisto/etc/issues/36189
> add new date formats

- src/components/Layouts/ReportLayout.less
Fixes <https://github.com/demisto/etc/issues/36270>
> add border to duration widget

- src/components/Sections/SectionChart/SectionBarChart.less
- src/components/Sections/SectionChart/SectionChart.less
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionLineChart.less
- src/components/Sections/SectionChart/SectionPieChart.less
fix line chart full height not considered when required
fix all charts height within the container
> Fix various charts height

- src/utils/strings.js
related to https://github.com/demisto/etc/issues/36571
> fix abbreviate format to support numbers bigger then billion

- reportService/reportsServer.js
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.less
- src/utils/sort.js
- templates/incidentDailyReportTempalte.json
- adding page offset (16px) when calculating height internally to make up for missing pixels in conversions
- fix page height incorrect scale when using headers not reflected in the dimensions
- fix bar chart does not respect reflectDimensions
- fix pie chart minor cut in print
> Fix page dimensions offset + chart offsets

- src/components/Sections/LabelAxisTick.js
- src/components/Sections/SectionChart/SectionBarChart.js
- src/constants/Constants.js
- src/utils/strings.js
Related <https://github.com/demisto/etc/issues/35902>
1) fix y axis bar charts
> Bar chart issues 

- reportService/reportsServer.js
- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionChart/SectionBarChart.less
- src/components/Sections/SectionChart/SectionLineChart.less
- src/css/variables.less
Fixes <https://github.com/demisto/etc/issues/36850>
> Fix Auto page break 

- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/LabelAxisTick.js
- src/components/Sections/SectionChart/SectionBarChart.js
- src/css/variables.less
Fixes <https://github.com/demisto/etc/issues/37207>
Fixes <https://github.com/demisto/etc/issues/36883>
Before 
After
> Fix widgets padding

- src/components/Sections/SectionChart/ChartLegend.js
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/utils/strings.js
Fixes https://github.com/demisto/etc/issues/36501
Support value formating for widgets y-axis and legend
https://user-images.githubusercontent.com/76961496/118964656-66f8f700-b970-11eb-9f61-261960a5d43d.mov
> Widget value formats

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
fixes https://github.com/demisto/etc/issues/37272
> move reference line on top of the graph

- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionChart.js
- src/constants/Constants.js
- src/utils/time.js
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/36530
Support date formating for bar chart
General examples:
https://user-images.githubusercontent.com/76961496/119260305-f0136680-bbda-11eb-8f47-ec1b56268850.mov
stacked examples:
https://user-images.githubusercontent.com/76961496/119355281-bf503180-bcad-11eb-83fa-4e3ba3213323.mov
> support date formating for bar chart

- src/components/Sections/SectionChart/SectionLineChart.js
Fixes https://github.com/demisto/etc/issues/37284
Support weeks format in line section
https://user-images.githubusercontent.com/76961496/119485424-ba4bba80-bd5f-11eb-8def-5568538e5ed7.mov
> support weeks format for line section

- src/components/Sections/SectionDuration.less
Related https://github.com/demisto/etc/issues/37421
Duration widget - improve layout
> improve duration section layout

- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionChart/SectionLineChart.js
Fixes https://github.com/demisto/etc/issues/37380
Fixes <https://github.com/demisto/etc/issues/37591>
before 
after
with force full
> fix reflect dimensions charts overflow

- src/components/Sections/SectionChart/SectionLineChart.js
- tests/containers/ReportContainer_spec.js
fixes <https://github.com/demisto/etc/issues/37580>
builder 
reports
> fix line chart - extra date added

- src/components/Sections/SectionChart/SectionChart.js
- src/constants/Constants.js
> remove show others - server will handle

- package.json
- src/components/Sections/SectionChart/SectionBarChart.js
- src/utils/sort.js
- src/utils/strings.js
- src/utils/validators.js
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/37382
**screenshots**
> Fix bug the legend keys were in different order

- src/components/Sections/SectionChart/SectionPieChart.js
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
fixes https://github.com/demisto/etc/issues/37630
Report builder:
report:
> show pie charts legend according to "hideLegend" field

- src/components/Sections/SectionChart/SectionLineChart.js
- src/utils/data.js
- src/utils/sort.js
Fixes https://github.com/demisto/etc/issues/37678
https://github.com/demisto/web-client/pull/8312
> sort legend by severity in section line chart

- src/components/Sections/SectionMarkdown.js
- src/utils/markdown.js
Rerated client PR: https://github.com/demisto/web-client/pull/8445
Report editor:
Actual report
> Add underline support to markdown

- src/components/Sections/SectionChart/SectionPieChart.js
- src/components/Sections/SectionChart/SectionPieChart.less
- templates/testLayout.json
- tests/containers/ReportContainer_spec.js
_related to https://github.com/demisto/etc/issues/38549_
**Given**
```
"layout": {
"chartProperties": {
"label": true
...
},
"chartType": "pie"
...
```
**→ Pie chart labels**
> pie charts labeling support

- src/components/Sections/SectionMarkdown.js
- src/utils/markdown.js
related web PR: https://github.com/demisto/web-client/pull/8475
How it looks in report:
how it looks in demisto:
> Add text alignment support for markdown

- src/components/Sections/SectionMarkdown.js
- src/utils/markdown.js
How it looks in demisto:
How it looks in Sane:
> Markdown - Add text style support

- src/office/csv/CSVReport.js
- templates/templateProvider.js
- templates/testLayoutCsv.json
- templates/testLayoutScriptBasedTable.json
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/40556
Add resolving logic for table data and columns in case of a csv report
> csv report with table based automation

- src/components/Layouts/ReportLayout.less
- src/components/Sections/SectionTable.js
- src/components/Sections/SectionTable.less
- src/utils/layout.js
- templates/testLayoutScriptBasedTable.json
https://github.com/demisto/etc/issues/38832
Styling table section & empty sections
> Style reports layout

- src/index.js
- src/utils/reports.js
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/41131
Fix page break bug
https://github.com/demisto/sane-reports/pull/183
> fix page break bug

- src/components/Sections/SectionChart/ChartLegend.less
- src/components/Sections/SectionDuration.js
- src/components/Sections/SectionDuration.less
Fixes https://github.com/demisto/etc/issues/37917 , https://github.com/demisto/etc/issues/41527
Enhance responsive typography:
- Improve responsive typography in duration widget
- WYSIWYG pie chart legend layout
> Enhance responsive typography

- src/components/Sections/ItemsSection.js
- src/components/Sections/SectionMarkdown.js
- src/utils/layout.js
- src/utils/reports.js
Make sure all markdown sections are getting the server attribute
> Markdown server proper support

- src/components/Sections/SectionMarkdown.js
- templates/templateProvider.js
- templates/testLayoutMarkdownWithCodeBlock.json
- tests/containers/ReportContainer_spec.js
fixes https://github.com/demisto/etc/issues/42605
screenshot:
after fix:
> fix unique keys for react components

- src/components/Sections/ItemsSection.js
- templates/templateProvider.js
- templates/testLayoutLongTextItemSection.json
- tests/containers/ReportContainer_spec.js
Fixes: https://github.com/demisto/etc/issues/43083
- Before:
- After:
> bugfix text overflow at section item

- tests/containers/ReportContainer_spec.js
at ci:
locally
because of unstable test
> Fix failing tests on master - adding more time to timeout

- src/components/Sections/ItemsSection.js
- src/components/Sections/SectionDate.js
- src/constants/Constants.js
- templates/templateProvider.js
- templates/testLayoutWithDateTime.json
- tests/containers/ReportContainer_spec.js
related to https://github.com/demisto/etc/issues/42120
fixes:
> Timestamps should be 'cut' after the minutes
> ![image](https://user-images.githubusercontent.com/73779436/137124009-6d1c24c6-86cc-4f7e-8003-08572c5c8f2d.png)
> Date Time better format when inside item section

- src/components/Sections/ItemsSection.js
- src/components/Sections/SectionDate.js
- src/constants/Constants.js
- tests/containers/ReportContainer_spec.js
- Remove "Date:" prefix
- Fix datetime format
> Fix section date time

- templates/templateProvider.js
- tests/containers/ReportContainer_spec.js
- tests/helpers/templateTestHelper.js
the importing of templates at tests makes the CI fall.
All CI tests pass.
> fix import legacy template at templateProvider.js

- .gitignore
small change - adding `out/` folder to gitignore
> adding 'out/' folder to gitignore

- README.md
- package.json
will help to create pdf files locally at the `out/` folder for developers on macos
> add test:macos script at package.json

- reportService/reportsServer.js
add top margin to the page
[2021-12-05_12-43-10_test.pdf](https://github.com/demisto/sane-reports/files/7656304/2021-12-05_12-43-10_test.pdf)
[2021-12-05_16-43-29_test.pdf](https://github.com/demisto/sane-reports/files/7656306/2021-12-05_16-43-29_test.pdf)
> fix margin top, enclose header and footer templates in regions

- reportService/reportsServer.js
Fixes <https://github.com/demisto/etc/issues/43468>
**reportsService script**
delete html template after generating report
> clean html template after generating report

- src/components/Layouts/ReportLayout.js
- src/components/Layouts/ReportLayout.less
- src/components/Sections/ItemsSection.js
- src/components/Sections/ItemsSection.less
- src/components/Sections/SectionMarkdown.js
- src/utils/layout.js
Fixes https://github.com/demisto/etc/issues/44641
Fields position issue - https://github.com/demisto/etc/issues/45346 
1. Revert border logic in code for items-section.
2. Refactor items-section to grid layout instead of absolute calculations
> text going out of the section borders

- src/components/Sections/ItemsSection.js
- src/utils/layout.js
- templates/testLayoutSingleItemSectionTitle.json
- tests/containers/ReportContainer_spec.js
Fixes https://github.com/demisto/etc/issues/44639
`Item section` - hide single item title
> hide-single-item-title-SANE

- package.json
- reportService/reportsServer.js
- reportsServer.js
- src/components/Sections/SectionDate.js
- tests/containers/ReportContainer_spec.js
When the date is `undefined`, render `N/A` instead of the current date.
> Fixes for date fallback to na 44252

- index.template.html
- reportService/reportsServer.js
- src/components/Sections/SectionTable.js
- src/constants/Constants.js
- src/index.js
Added the ability to configure max table length (default stays 300 as before)
fixes https://github.com/demisto/etc/issues/38975
related changes
content: https://github.com/demisto/content/pull/17914
platform: https://code.pan.run/xsoar/server/-/merge_requests/17688
> configure max table length

- src/utils/layout.js
Fixes https://github.com/demisto/etc/issues/47448
Hide empty table - fix condition to not throw exception in case of null data
> improve condition for hiding empty table to verify null data

- src/components/Sections/SectionMarkdown.js
- src/constants/Constants.js
fixes https://jira-hq.paloaltonetworks.local/browse/XSUP-13995
> check if markdown image path also starts with account name for MT support

- src/utils/layout.js
Support date sections with the current time.
Related Issue: CRTX-64873
Related PRs: https://github.com/demisto/sane-reports/pull/217
> CRTX-64873: Support date sections with the current time

- src/utils/markdown.js
- tests/utils/markdown_spec.js
FE related issue: https://github.com/demisto/etc/issues/42844
cherry pick https://code.pan.run/xsoar/web-client/-/merge_requests/7013
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-17606
> fix markdown section infinite loop

- src/components/Sections/SectionDate.js
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/10021671/incidentDailyReportTempalte.pdf)
> CRTX-64077: Display closed time as N/A

- .babelrc
- package.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
> Support optional chaining

- .babelrc
- package.json
- src/components/Sections/SectionChart/SectionBarChart.js
- src/components/Sections/SectionChart/SectionLineChart.js
- src/components/Sections/SectionChart/SectionPieChart.js
- src/utils/charts.js
template: [incidentDailyReportTempalte.txt](https://github.com/demisto/sane-reports/files/10049922/incidentDailyReportTempalte.txt)
report before:[incidentDailyReportTempalte-master.pdf](https://github.com/demisto/sane-reports/files/10050011/incidentDailyReportTempalte-master.pdf)
report after:[incidentDailyReportTempalte-CRTX-67937.pdf](https://github.com/demisto/sane-reports/files/10050012/incidentDailyReportTempalte-CRTX-67937.pdf)
app:
> CRTX-67937: Fix decimal values charts

- src/components/Sections/ItemsSection.js
I used the same solution we already use with the table widgets.
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/10743734/incidentDailyReportTempalte.pdf)
https://user-images.githubusercontent.com/73780437/219049064-dacdd16e-6057-41c0-a450-9b42550775ef.mov
> CRTX-75449: Grid field - Support passing which columns to display and their order

- src/components/Sections/SectionDate.js
server already formatting the section date data.
currently, sane is formatting the data using a hard coded format and its own TZ (running machine)
> refactor date format condition

- src/components/Sections/ItemsSection.js
- src/components/Sections/SectionTable.js
- src/utils/layout.js
- templates/testLayoutIncidenInfo.json
- templates/testLayoutWithTableSection.json
JSON: templates/testLayoutIncidenInfo.json
Generated Report: [testLayoutIncidenInfo.pdf](https://github.com/demisto/sane-reports/files/12782156/testLayoutIncidenInfo.pdf)
JSON: templates/testLayoutWithTableSection.json
Generated Report: [testLayoutWithTableSection.pdf](https://github.com/demisto/sane-reports/files/12782128/testLayoutWithTableSection.pdf)
> CRTX-94595: Table section didn't have the original column width

- src/components/Sections/SectionDuration.js
Missing values in duration if the number of digits is more than 2 digits
[incidentDailyReportTempalte.json](https://github.com/demisto/sane-reports/files/13449180/incidentDailyReportTempalte.json)
[Before.pdf](https://github.com/demisto/sane-reports/files/13449179/Before.pdf)
[After.pdf](https://github.com/demisto/sane-reports/files/13449177/After.pdf)
> CRTX-98385: Missing values in duration if the number of digits is more than 2 digits

- README.md
- src/components/Layouts/ReportLayout.less
Reverts demisto/sane-reports#259
[incidentDailyReportTempalte.json](https://github.com/demisto/sane-reports/files/13861177/incidentDailyReportTempalte.json)
[before.pdf](https://github.com/demisto/sane-reports/files/13861179/before.pdf)
[after.pdf](https://github.com/demisto/sane-reports/files/13861178/after.pdf)
> Revert "CRTX-96742: Broken tables in the PDF report Investigation summary"

- src/components/Sections/SectionMarkdown.js
- src/utils/markdown.js
[incidentDailyReportTempalte.json](https://github.com/demisto/sane-reports/files/14815060/incidentDailyReportTempalte.json)
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/14815064/incidentDailyReportTempalte.pdf)
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/14815063/incidentDailyReportTempalte.pdf)
From the before report:
From the after report:
----
[testLayoutInvestigationSummaryReport.json](https://github.com/demisto/sane-reports/files/14815067/testLayoutInvestigationSummaryReport.json)
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/14815078/incidentDailyReportTempalte.pdf)
[incidentDailyReportTempalte.pdf](https://github.com/demisto/sane-reports/files/14815073/incidentDailyReportTempalte …
> CRTX-111037: Incomplete Display of Information in XSOAR Report Exports
